- docker-compose.yml
Closes #1 
* Added a DB health check to the `docker-compose.yml` file.
1. Start up docker containers a few times and make sure that the PostgreSQL database is up.
* Correct implementation and functionality of the db health check
> Add health check to docker-compose.yml

- .github/workflows/lint.yml
- backend/graphql/index.ts
- backend/graphql/resolvers/authResolvers.ts
- backend/graphql/resolvers/entityResolvers.ts
- backend/graphql/resolvers/userResolvers.ts
- backend/middlewares/auth.ts
- backend/middlewares/validators/authValidators.ts
- backend/middlewares/validators/entityValidators.ts
- backend/middlewares/validators/userValidators.ts
- backend/middlewares/validators/util.ts
- backend/migrate.js
- backend/models/entity.model.ts
- backend/models/index.ts
- backend/models/user.model.ts
- backend/package.json
- backend/server.ts
- backend/services/implementations/__tests__/userService.test.ts
- backend/services/implementations/authService.ts
- backend/services/implementations/entityService.ts
- backend/services/implementations/fileStorageService.ts
- backend/services/implementations/userService.ts
- backend/testUtils/testDb.ts
- backend/utilities/firebaseRestClient.ts
- backend/utilities/logger.ts
- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/APIClients/EntityAPIClient.ts
- frontend/src/components/auth/Signup.tsx
- frontend/src/components/crud/DisplayTableContainer.tsx
- frontend/src/index.tsx
Closes #22
*  create `.github/workflows/super-linter.yml` to run linter whenever code is pushed to `main`, PRs are made to `main`
* allow linter to be started manually
1. branch off of `daniel/github-action`
2. make a PR with bad formatting
3. see if linter finds the error
> Create GitHub Workflow for Linting

- backend/package.json
- docker-compose.yml
N/A
* Explicitly set container names in docker-compose.yml so that it is deterministic
* Run `npx prisma generate` as part of backend's `dev` script
1. Run the application (important: update `DB_HOST` in root `.env` file to be sistering_db)
```bash
docker-compose up --build
docker ps
```
You should see these container names:
2. Check that the `prisma generate` command ran as part of the backend `dev` script, you should see logs like this:
```
backend_1   | Environment variables loaded from prisma/.env
backend_1   | Prisma schema loaded from prisma/schema.prisma
backend_1   |
backend_1   | ✔ Generated Prisma Client (3.3.0) to ./node_modules/@prisma/client in 1.10s
backend_1   | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
backend_1   | ``` …
> Set container names and update backend dev script to include prisma generate command

- backend/graphql/index.ts
- frontend/src/App.tsx
- frontend/src/components/auth/DoneResetPassword.tsx
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/ResetPassword.tsx
- frontend/src/components/pages/Default.tsx
- frontend/src/constants/Routes.ts
Closes #28 
* Moved reset password button to login screen and removed it from our homepage
* Removed auth check for resetPassword endpoint
* Uses a user-inputted email as reset target
1. Go to login page
2. Click reset reset password
3. Enter email to reset password (both valid emails and invalid)
4. If valid, follow email prompts to reset password
5. Return to login
6. Try using the new password
* Nothing in particular - it's a rather simple ticket with a small number of changes
> Moved Forget Password to Landing Page

- .gitattributes
- .gitignore
N/A
* Added .gitattributes file
* Added rule that sets line endings to LF for shell scripts (many Windows users have `autocrlf` git settings enabled which automatically converts line endings to CRLF locally - however Docker is unable to scripts with CRLF, e.g. the `db-init/create-multiple-dbs.sh` script)
After this PR is merged, Windows users should pull on `main` and ensure that shell scripts have LF line endings
* N/A
> Add .gitattributes file with line endings rule

- backend/services/implementations/authService.ts
- backend/services/implementations/branchService.ts
- backend/services/implementations/emailService.ts
- backend/services/implementations/entityService.ts
- backend/services/implementations/fileStorageService.ts
- backend/services/implementations/postingService.ts
- backend/services/implementations/shiftService.ts
- backend/services/implementations/skillService.ts
- backend/services/implementations/userService.ts
- backend/utilities/errorUtils.ts
Closes #99 
* Added a `getErrorMessage` utility function
* Replace all errors with type `unknown`
* Replaced current Logger messages to use `getErrorMessage`
1. Make sure that application runs as expected and errors are being logged properly
* Didn't miss any errors to be replaced
> Implement type safe error handling

- frontend/src/App.tsx
- frontend/src/components/pages/admin/posting/CreatePostingShiftsPage.tsx
- frontend/src/constants/Routes.ts
Closes #87 
- Add a page for admin posting (located in frontend/src/components/pages/admin/posting/CreatePostingShiftsPage.tsx). Empty div.
- PrivateRoute added for new page
1. route `/admin/posting/create/shifts` should return 404 when logged in as authenticated user
* Commit msg ok?
* Right type of route used?
> Create page for Admin Posting

- frontend/src/components/auth/Login.tsx
N/A, just a quick fix to display Google login error details properly.
* Correctly typed the Google login error response for future reference
* Stringified error object in alert message, otherwise it will display as `[Object object]`
1. Click on the preview deploy link below
2. Error message should be as follows:
```json
{
"error": "idpiframe_initialization_failed",
"details":"Not a valid origin for the client: https://sistering-dev--pr78-sherry-google-login-ulm92vdz.web.app has not been registered for client ID 1076597678761-u9ek25jknj77d37atud522vb4ri1385t.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and register this origin for your project's client ID."
}
```
Note that this error is expected because the preview URL is not listed as an authorized …
> Alert Google login error details

- README.md
- backend/prisma/migrations/20220128011600_remove_availability_and_prereq/migration.sql
- backend/prisma/schema.prisma
Closes #94
* Remove deprecated tables
* Add migration file via `npx prisma migrate dev --name remove_availability_and_prereq`
* Add sample instruction to readme regarding migration files
1. App still runs, user can still log in as needed
* If there are any missing fields left
* If generated migration file is okay
* If readme is okay
> Remove availability and prereq table from schema

- frontend/src/components/pages/Default.tsx
- frontend/src/theme/index.ts
Closes #132 
* The default tag style is now green with dark green text 
* the outline variant is now text.gray
Implementation:
Designs:
> Add tag styling to theme

- backend/graphql/index.ts
- backend/graphql/resolvers/userResolvers.ts
- backend/graphql/types/postingType.ts
- backend/graphql/types/userType.ts
- backend/prisma/migrations/20220130202413_remove_user_id_field_for_employee_model/migration.sql
- backend/prisma/schema.prisma
- backend/services/implementations/postingService.ts
- backend/services/implementations/userService.ts
- backend/services/interfaces/userService.ts
- backend/types.ts
Addresses second half of #29 
* Implement CRUD methods:
- getEmployeeUserById
- getEmployeeUserByEmail
- getEmployeeUsers
- createEmployeeUser
- updateEmployeeUserById
- deleteEmployeeUserById
- deleteEmployeeUserByEmail
* Create corresponding GraphQL resolvers and DTOs
1. Start docker and run `docker-compose up --build`
2. Apply the lasted migration files by running `docker exec -it sistering_backend /bin/bash` and `npx prisma migrate deploy`. 
3. We need row(s) in the posting and branch tables for testing. You can either create those using the corresponding GraphQL endpoints or use raw SQL. 
4. Go to http://localhost:5000/graphql
5. Login using an admin user 
6. Then verify that all GraphQL queries and mutations introduced in this ticket work as expected
* Verify that GraphQL endpoints …
> Add EmployeeUser CRUD and GraphQL Resolvers

- backend/prisma/migrations/20220217223601_modify_branch_id_on_employee_model/migration.sql
When pulling the latest changes from main and running `npx prisma migrate dev`, it generates this migration. It looks like the prev change to this index in `backend\prisma\migrations\20220130202413_remove_user_id_field_for_employee_model\migration.sql` doesn't  include `ON UPDATE`. 
Anyone know why this is happening? .-.
> Modify  branch id field on employee model

- frontend/src/components/admin/posting/CreatePostingReview.tsx
- frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
Closes #88 
* Added the create posting mutation in `CreatePostingReviewPage`
* Added two buttons ("Save as Draft" and "Post") in `CreatePostingReviewPage` that call the create posting mutation
* Save as Draft: creates posting with status `DRAFT`
* Post: creates posting with status `PUBLISHED`
* `CreatePostingReviewPage` gets posting data using `PostingContext`
1. Run the application locally `docker-compose up --build`
2. Create a branch in your local database for the posting to use
3. Click on the "Edit Posting" tab on the default page and enter the branch id of the branch you just created. 
4. Add other dummy information (be sure to include the dates for "Start Date", "End Date", and "Auto-Closing Date").
5. Click on the "Review Posting" tab and click the "Save as Draft" or "Post" button …
> Add API call functionality to create posting

- backend/package.json
- backend/prisma/seed.ts
- backend/utilities/dateUtils.ts
Closes #92
Ask me for the UIDs of the test users to add to your .env.
run `docker exec -it sistering_backend bash -c "npx prisma db seed"` to run just the seed script **or**  `docker exec -it sistering_backend bash -c "npx prisma migrate reset"` to replace data in your current db with seed data. 
Try logging in as a test user. The password for all test users is Test123.
* Check that users, branches, skills, shifts, postings, etc. are generated properly.
> Generate Seed Data

- backend/graphql/resolvers/shiftSignupResolvers.ts
- backend/graphql/types/shiftSignupType.ts
- backend/services/implementations/shiftSignupService.ts
- backend/services/interfaces/shiftSignupService.ts
Closes #126
* To add filtering by signups to our `getShiftSignupsForUser` endpoint, I added an optional argument for specifying the status of the signup.
* `getShiftSignupsForUser(id)` -> `getShiftSignupsForUser(id, status)`
1. You can populate the db into a testable state by running the commands found in this [PR](https://github.com/uwblueprint/sistering/pull/90)
2. Create some signups using mutations. For example: `mutation {
createShiftSignups(
shifts: [{ shiftId: 3, userId: 1, numVolunteers: 3, note: "test" }]
) {
shiftId
userId
numVolunteers
note
}
}`
3. Test various scenarios to see if the filtering works as expected.
* Test to see if the filtering works as behaved.
> Add filtering by status to signups

- frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
- frontend/src/components/volunteer/EmptyPostingCard.tsx
- frontend/src/components/volunteer/PostingCard.tsx
- frontend/src/types/DateFilterTypes.ts
- frontend/src/types/api/EmployeeTypes.ts
- frontend/src/types/api/PostingTypes.ts
- frontend/src/utils/DateUtils.ts
Closes #82 #83 #117
- refactor posting card according to comments on PR
- created a page that displays events and regular volunteer opportunities (/volunteer/postings), fetches data via a graphQL query
- created an empty event component to display in the case where there are no active events / regular volunteer opportunities
- create filter feature for week/month/all shifts timeframes
Navigate to http://localhost:5000/graphql and run the mutation (see: https://github.com/uwblueprint/sistering/pull/140) multiple times with different startDates 
Navigate to http://localhost:3000/volunteer/postings and verify: 
- API call receives the correct data
- Implementation UI matches Figma for #83 Volunteer Browse Postings Page
- Verify the definition of what an volunteer opportunity/event is (line …
> Complete volunteer posting card, postings page, postings filter

- frontend/src/App.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
- frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
- frontend/src/constants/Routes.ts
Closes #144 
* Added a `/not-found` route for `NotFound.tsx` component
* In `VolunteerPostingDetails.tsx`, redirect to `/not-found` when posting does not exist
* Note: I had to change the way the `postingDetails` variable was being set when calling `useQuery`, because before, `loading` and `postingDetails` could be `false` **and** `null` at the same time even though the posting exists
1. Go to `/volunteer/posting/{id}` and replace id with a posting id you have created in your local database
2. Check that the page still loads when the posting exists
3. Try changing the id to one that does not exist and check that the page redirects to not found
> Redirect to 404 page when posting does not exist

- backend/graphql/index.ts
- backend/middlewares/auth.ts
Closes #115
* Created `isAuthorizedForCreateShiftSignups` check for `createShiftSignups` and `isAuthorizedForUpdateShiftSignups` check for `updateShiftSignup`
1. Ensure that your local db contains the [seed data
](https://uwblueprint.slack.com/archives/C02CN0ZAZDG/p1645395343075529)
2. `docker-compose up --build`
3. Navigate to http://localhost:5000/graphql 
4. Run the following mutations and ensure the results are expected (Credits for the mutations to Joseph from #90 🙏).
Sign in as a volunteer and use the access token for the following mutations:
```graphql
mutation {
createShiftSignups(
shifts: [{ shiftId: 2, userId: 1, numVolunteers: 3, note: "test" }]
) {
shiftId
userId
numVolunteers
note
}
}
mutation {
createShiftSignups(
shifts: [{ shiftId: 2, userId: 2, numVolunteers: 3, note: …
```
> Add Support for Nested Fields in isAuthorizedByUserId for Retrieving UserId

- frontend/src/App.tsx
- frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
- frontend/src/constants/Routes.ts
Closes #194
* Created the component `AdminSchedulePostingPage`
1. Go to `http://localhost:3000/admin/schedule/posting/X` where is an `id` of your choosing.
2. Check to see the page exists and the `id` is retrieved correctly.
* Check to see if the page exists. Nothing too tough about this one.
> Create AdminSchedulePostingPage 

- backend/graphql/types/shiftSignupType.ts
- backend/services/implementations/shiftSignupService.ts
- backend/types.ts
Closes #195
* Denormalize typing as required
* Add new converter method for denormalized response type
1.
NOTE: This PR has not been tested yet. would like some quick pointers
* correctness
> Denormalize signup res and query types

- backend/graphql/types/shiftSignupType.ts
- backend/prisma/migrations/20220320210021_add_published_signup_status/migration.sql
- backend/prisma/schema.prisma
- backend/types.ts
Closes #209 
* added a published status to the signupStatus enum to shiftSignupType.ts, schema.prisma, and types.ts
* adding published to enum is implemented properly 
- [x ] My PR name is descriptive and in imperative tense
- [x ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ x] I have run the appropriate linter(s)
- [ x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
> Add Published to Signupstatus Enum

- frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
- frontend/src/components/common/TagsPopover.tsx
Closes #192 
* Used Chakra UI popover components to create popover for skill and employee tags in create posting basic info form
* There was a small issue where the text in the skill and employee tags were not being center aligned - fixed this by removing the `TagLabel` component that wrapped around the text
1. Go to the create posting info form
2. Add some skills and employees. Note: you may have to create more skills and employees in the database to test the popover functionality
3. Once you have more than 2 skills or employees selected, you can click the +`x` tag (where `x = [number of selected tags] - 2` to see the popover
* Is it okay to remove the `TagLabel` component? I didn't use it for the tags in the review postings page, not sure if it's required.
> Implement skill and employee tag popovers

- backend/graphql/index.ts
- backend/graphql/resolvers/shiftSignupResolvers.ts
- backend/graphql/types/shiftSignupType.ts
- backend/services/implementations/shiftSignupService.ts
- backend/services/interfaces/shiftSignupService.ts
Closes #190 
* Add simple query to get signup shifts by posting ids
1. create signup shifts of posting
2. call query to get created queries
* correctness
> Add signup shifts query by posting id

- frontend/src/components/auth/ResetPassword.tsx
Closes #215
* Add reset password component according to design
1. Login as admin
2. Go to `/reset-password`
3. Ensure design works as expected as specified in ticket
* Look and feel
> Add reset password page component

- backend/graphql/index.ts
- backend/graphql/resolvers/shiftResolvers.ts
- backend/graphql/types/shiftType.ts
- backend/services/implementations/shiftService.ts
- backend/services/interfaces/IShiftService.ts
- frontend/src/App.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
- frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
- frontend/src/components/volunteer/shifts/VolunteerAvailabilityTableRow.tsx
- frontend/src/constants/Routes.ts
- frontend/src/types/api/SignupTypes.ts
Closes #129 
https://user-images.githubusercontent.com/44826218/158919383-94b72bb3-b2ac-4821-80a5-f92417faa9f7.mp4
- Added base page for select shift
- Added top level shift saving with notes
- Added new note type for client side prop drilling
- Added get shift by posting id query
- Created page called `/volunteer/posting/:id/availabilities` which does a datafetch on shifts and posting details for table
1. Run seed and go to  `/volunteer/posting/:id/availabilities` for id 1 and 2
2. Table page should work properly - checkboxes should persist through pagination
3. On press on submit, console log all selected shifts from top level page (used later for submission query)
* Correctness + edge cases not in ticket
* Any redundancy
* Frontend layout
> Volunteer select availability table datafetch newpage

- backend/graphql/index.ts
- backend/graphql/resolvers/shiftResolvers.ts
- backend/graphql/types/shiftType.ts
- backend/services/implementations/shiftService.ts
- backend/services/interfaces/IShiftService.ts
- frontend/src/App.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
- frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
- frontend/src/components/volunteer/shifts/VolunteerAvailabilityTableRow.tsx
- frontend/src/constants/Routes.ts
- frontend/src/theme/index.ts
- frontend/src/types/api/SignupTypes.ts
- frontend/src/utils/DateTimeUtils.ts
Closes #120, #119, #129
* Add volunteer select availability table
* Enhanced base components for better padding, highlighted background on select, disabled input when not selected
TODO:
- change prop type from postingId to posting type (@uwblueprint/sistering-w22-pls  I'm not sure what type I should use here). This can honestly be done in the integration step
1. Play around with the test page on the `volunteer/posting` route
2. input should be disabled if shift checkbox is not selected
3. background should highlight when shift selected
4. page should display current week from sun to sat correctly with appropriate shifts in each table section
* Design: look and feel
* Dev: Implementation of table
> Add volunteer select availability table

- frontend/src/components/common/PostingDetails.tsx
Closes #131 
* Wrapped the postingDetails description inside the RichTextDisplay component created in #130 
1. Follow testing instructions in https://github.com/uwblueprint/sistering/pull/140 , but replace the description field of the createPosting mutation with the following richText samples:
- "{\"blocks\":[{\"key\":\"2ggjh\",\"text\":\"hi\",\"type\":\"ordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"2nlb2\",\"text\":\"aewf\",\"type\":\"ordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":4,\"style\":\"BOLD\"}],\"entityRanges\":[],\"data\":{}},{\"key\":\"6a81d\",\"text\":\"asf\",\"type\":\"ordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":3,\"style\":\"BOLD\"},{\"offset\":0,\"leng …
> Use RichTextDisplay in posting details page

- frontend/src/components/volunteer/PostingCard.tsx
N/A, just spotted a use of richtext that we missed.
* Wrapped posting description in `RichTextDisplay` component
1. Run the application with seed data
2. Navigate to localhost:3000/volunteer/postings
3. Verify that the posting description is properly formatted (not JSON string)
4. Check the truncate behaviour (max 2 lines of description displayed in card). Create a temporary rich text string in PostingCard.tsx and pass into RichTextDisplay
```ts
const richTextSample = '{"blocks":[{"key":"2ggjh","text":"hi","type":"ordered-list-item","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"2nlb2","text":"aewf","type":"ordered-list-item","depth":0,"inlineStyleRanges":[{"offset":0,"length":4,"style":"BOLD"}],"entityRanges":[],"data":{}},{"key":"6a81d","text":"asf","type":"ordered …
```
> Integrate RichTextDisplay into PostingCard component

- frontend/src/components/admin/schedule/AdminScheduleTable.tsx
- frontend/src/components/admin/schedule/AdminScheduleTableDate.tsx
- frontend/src/components/admin/schedule/AdminScheduleTableRow.tsx
- frontend/src/components/pages/Default.tsx
- frontend/src/theme/colors.ts
Closes #156 
Closes #158 
* Implemented the **schedule review table** and its table rows, which display all volunteer shifts of a certain week.
* Note that this table implementation is only for displaying the shifts in one week (passed in via props), and does not include the date navigation header.
1. Add the following code to `Default.tsx`, importing components/variables when necessary:
```
<Container maxW="container.xl">
<AdminScheduleTable schedule={TableTestData} />
</Container>
```
2. Check http://localhost:3000/ to see that `TableTestData` is rendered correctly. The test data includes three types of table rows, as specified in #156.
* Clean React code, correct separation of concern for the props & states.
* Stay hydrated 💧
> Create admin schedule review table

- frontend/src/components/common/PostingDetails.tsx
- frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
- frontend/src/components/volunteer/PostingCard.tsx
Closes #255 
* In addition to posting card links, links also added for posting details pages
* Knowledge of routing is kept at the page-level and passed into components as props - feedback on this approach is welcome
1. Click on the preview deploy link
2. Navigate to `/volunteer/postings` and check that the posting details and submit availabilities links on the cards work
3. Check links on posting details pages (`/volunteer/posting/:id` and `/admin/posting/:id`)
* Where does the routing responsibility belong?
> Link posting cards to details and submit availabilities pages

- backend/graphql/resolvers/postingResolvers.ts
- backend/graphql/types/postingType.ts
- backend/services/implementations/postingService.ts
- backend/services/implementations/shiftService.ts
- backend/services/interfaces/IShiftService.ts
- backend/services/interfaces/postingService.ts
- backend/types.ts
- frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
- frontend/src/types/api/PostingTypes.ts
Closes #244 
* Created a new method called `bulkGenerateTimeBlocks` that will verify and create an array of TimeBlocks to be used creating a posting
* `CreatePosting` now generates shifts along with the posting
* Front end of the Create posting review page has been updated to match the modified endpoint
1. Create a new posting (try recurring and non-recurring shifts) through the UI
2. After submitting, query for the posting and check that it was created properly with the associated shifts
```
query Postings {
postings {
id
title
description
startDate
endDate
status
shifts {
startTime
endTime
}
}
}
```
*  Shifts are generated with the same logic as before
> Create shifts with posting

- frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
- frontend/src/components/admin/posting/CreatePostingShifts.tsx
- frontend/src/contexts/admin/PostingContext.ts
- frontend/src/types/PostingContextTypes.ts
Closes #233 
* Set initial values in create basic info and shift pages to be values from the posting context
* Note context is updated on "Next", so previous values can only be retrieved if "Next" was clicked prior to navigating away
1. Click preview deploy link
2. Navigate to create posting page
3. Enter info on each page and test navigating forward/back with the "Next" and "Back" buttons, the previously entered data should be preserved
* Does it work?
* See comments
> Load initial create posting values from context

- backend/graphql/index.ts
- backend/graphql/resolvers/shiftSignupResolvers.ts
- backend/graphql/types/shiftSignupType.ts
- backend/services/implementations/shiftSignupService.ts
- backend/services/interfaces/shiftSignupService.ts
- backend/types.ts
- frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
- frontend/src/types/api/SignupTypes.ts
Closes #258
* Add mutation call that does delete then upsert on signup shifts
* New mutation call has new types added
NOTE: Only the backend mutation is completed, not integrated into client at the moment.
1. Create new signups
2. Use the new mutation call to update and delete some signups in the same graphql mutation
* Correctness
* New Typing
> Add submit signups mutation to availability page

- frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
Closes #257 
* Added redirect after submission of `VOLUNTEER_POSTING_AVAILABILITIES` page
* Displayed success toast on `VOLUNTEER_POSTING_DETAILS` page
* Research was asked to be done on persisting the toast, but it looks like it's natively supported by Chakra UI - nothing special had to be done.
1. Go to `/volunteer/posting/:id/availabilities`
2. Click submit
3. Ensure redirect occurs and success toast is visible
* The functionality in steps to test. It is a pretty simple PR
> Redirect to posting details page and display success toast upon submitting availability

- frontend/src/contexts/admin/PostingContext.ts
Closes #282 
* Updated the `numVolunteers` value to 1 in the default posting context
* "snap to default" behaviour in number input will ensure that user cannot set the value to 1
1. Click the preview deploy link
2. Go to the create posting page, verify that the initial number of volunteers shown is 1
3. Try to change the value to 0, verify that it is "snapped" to 0
* N/A
> Update default numVolunteers to 1 in default posting context

- frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
Closes #272
* Changed the input value to be a string and made sure to parse the string when clicking the `Next` button.
* If parse fails, then displays an error
1. Go to `http://localhost:3000/admin/posting/create/basic-info`
2. Try various values for num volunteers input and click Next button (check if behaviour seems correct)
* Just the behaviour of the num volunteers input
> Fix num volunteers input for admin posting flow NaN bug

- frontend/src/components/admin/ShiftCalendar/MonthViewShiftCalendar.tsx
- frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
- frontend/src/components/pages/Default.tsx
- frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
- frontend/src/utils/DateTimeUtils.ts
Closes #178 
* Created a header for the monthly shift calendar that allows navigation between months.
* The header includes the following:
* Next month button if there are shifts after this month
* Previous month button if there are shifts before this month
* Month dropdown to display each month with shifts
* As per discussions with @krystaltruong:
* The header navigation will start at the earliest event (start date) by default.
* If there is a month in between with no events, it will still be included in the navigation. (For example, May 2022 in `ADMIN_SHIFT_CALENDAR_TEST_EVENTS` is still displayed). 
1. Navigate to `http://localhost:3000/admin/schedule/posting/{id}` to see `ADMIN_SHIFT_CALENDAR_TEST_EVENTS` displayed.
* Potential edge cases?
> Implement monthly calendar header

- frontend/src/components/admin/ShiftCalendar/WeekViewShiftCalendar.tsx
- frontend/src/components/admin/posting/CreatePostingShifts.tsx
Closes #284 and #285
new side effects: user must now select a start and end date before select a shift time on the calendar, times on the calendar out of the start-end date range is grey (see below)
* added a selectConstraint prop that disables users from being able to drag multi day events
* added a validRange prop based on the selected start and end dates
* see documentation: https://fullcalendar.io/docs/selectConstraint, https://fullcalendar.io/docs/validRange
1.http://localhost:3000/admin/posting/create/basic-info, enter any necessary info and click next to "Scheduling Time Slots"
2. Select a start and end date in the same week (such as Tues-thurs), try adding an event on Friday (this should be disabled) 
3. In the calendar, try dragging your mouse over an event that spans over …
> disable admin from creating multi-day shifts

- frontend/src/components/admin/ShiftCalendar/MonthViewShiftCalendar.tsx
- frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
- frontend/src/components/admin/schedule/AdminScheduleTable.tsx
- frontend/src/components/admin/schedule/ScheduleSidePanel.tsx
- frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
1. Go to /admin/schedule/posting/1
2. Click on a day
3. Check that the shifts filter to that day
There is a bug for some shift times (seems to be the ones closer to 12 like 1am-3am so it may be due to timezone issues) where the day the shift is being displayed on the calendar is +/- 1 day of the actual shift date :') But it should work sometimes so...yah
> filter by day click

- frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
- frontend/src/components/auth/Login.tsx
- frontend/src/components/pages/Default.tsx
- frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
- frontend/src/utils/DateTimeUtils.ts
Closes #324 #329 #336 #332 
Each commit corresponds to solving a different bug:
1. The calendar dates in the Admin Scheduling flow are now being converted to UTC. This means that when clicking on a day, the user will be able to choose 
2. For the volunteer postings flow, for the autoClosingDate filter when we fetch all postings, we were previously calling `new Date().getISOString()`. This will convert the current date, in whatever timezone you're in, to UTC. However, depending what timezone you're in and what time it is, if you are searching for posting on May 15, for example, we may be querying for postings with an autoclosing date greater or equal to May 16 (because getISOString() converts the date to UTC). Instead, we want to get the current day that is local to you and use that for …
> Fix side panel big, schedule calendar display bug, volunteer postings bug

- frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
- frontend/src/components/admin/schedule/AdminScheduleTable.tsx
- frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
- frontend/src/types/api/SignupTypes.ts
Closes #362 
* Change the signup status to `PUBLISHED` when user clicks Publish 
1. Use an existing posting with signups
2. Go to `/admin/schedule/posting/{id}`
3. Click on a day with signups, checkmark some signups, click save.
4. Repeat 4 for a couple other days.
5. Click Review
6. Check that the signups in the table match the ones you checkmarked.
7. Click Publish
8. Login as a volunteer whose signup was published.
9. Go to `volunteer/shifts`, check that the correct shifts are under `Upcoming Shifts` (you may need to change the filter)
> Publish admin schedule

- frontend/src/components/admin/ShiftCalendar/MonthViewShiftCalendar.tsx
Closes #359
* Set initial month in shift calendar such that it doesn't reset itself every time it re-renders. If the selected month is new Date(0) (the epoch time), we reset it to first date in shift otherwise we leave it alone
https://user-images.githubusercontent.com/44826218/170158822-d6556034-1b62-4926-9aeb-e6b2c29fdc10.mp4
1. Add a shift to a posting such that it stretches' 2 months
2. Go http://localhost:3000/admin/schedule/posting/1
3. Go to last month and select a day
* Correctness of fix
> Fix initial month state for MonthViewShiftCalendar

- frontend/src/components/admin/ShiftCalendar/MonthViewShiftCalendar.tsx
- frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
- frontend/src/components/admin/schedule/ScheduleSidePanel.tsx
- frontend/src/components/admin/schedule/ShiftTimeHeader.tsx
- frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
Closes #338 
* Centralize selected shift state in top-level admin calendar component from calendar sidebar
* add eventClick to call drilled handler for setting selected shift
* change sidebar select shift header to strictly use `value` prop for consistency with selected shift
1. login as admin and go to http://localhost:3000/admin/schedule/posting/1
2. make small changes to shift times for a date with more than 1 shift (to differentiate between shifts on the same day)
3. click on each shift in the calendar individually and ensure sidebar header and table jumps to corresponding shift
4. ensure no regression occurred with calendar
* correctness and cleanness
* no regression is introduced
> Add eventClick to full calendar to open sidebar to shift

- frontend/src/components/admin/ShiftCalendar/WeekViewShiftCalendar.tsx
Closes #331 
* Set reset scroll time prop to false prevents calendar from rendering scroll time
1. Go to `/admin/posting/create/shifts` and fill out the form
2. Try creating shifts at 3am, 9pm, or times that requires scrolling outside the view of 9am
3. Calendar should no longer re-render and scroll to 9am after creating a new shift on the calendar
* correctness
> Don't reset scroll time for weekly calendar jumping bug

- frontend/src/components/admin/DeleteModal.tsx
Closes #400 
* To give the current "delete" modal a bit more flexibility to fit in the use case of the remove user modal, which has "remove" as its delete text instead of "delete", we made the text a prop.
1. In `default.tsx` used this snippet:
```
const { isOpen, onOpen, onClose } = useDisclosure();
<Button onClick={onOpen}>Open Modal</Button>
<DeleteModal
title="heyo"
isOpen={isOpen}
body="this is the body. wow much text!"
confirmText="Remove"
onClose={onClose}
onDelete={() => alert("wow!")}
/>
```
> Remove User Modal

- frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
Closes #409
* On save, we did not update the selected shift state in the sidebar which would be an outdated copy after saving the state
* This PR saves the selected shift state on save
1. Sign up as admin and go to /admin/schedule/posting/1
2. Try to change status of a signup and save
3. The change shoudl reflect on the sidebar and the calendar
> Update selected shift state for sidebar on save

- frontend/src/components/volunteer/shifts/VolunteerPendingShiftsTableRow.tsx
- frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
- frontend/src/components/volunteer/shifts/VolunteerShiftsTableEmptyState.tsx
- frontend/src/components/volunteer/shifts/VolunteerUpcomingShiftsTable.tsx
- frontend/src/components/volunteer/shifts/VolunteerUpcomingShiftsTableRow.tsx
Closes #433
* Separate unrelated tables under `VolunteerShiftsTable`
* Create a new `VolunteerUpcomingShiftsTable` based on the existing `VolunteerAvailbilityTable`
1. Go to http://localhost:3000/volunteer/shifts ensure the tables on the my shifts and pending confirmation tabs looks good on empty case and non-empty case
* Correctness and cleanliness
> Polish upcoming volunteer shifts table to match design

- frontend/src/components/volunteer/shifts/VolunteerPendingShiftsTableRow.tsx
- frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
Closes #434 
* There's a new set (state not needed, just a set) called `uniquePostingIds`
* Before mapping `pendingShifts`, we filter it by checking if a shift's posting id is in the set
* If it is in the set, don't keep it as it is a duplicate, otherwise keep it and add the posting id to the set to avoid further duplicates
* This filtered `pendingShifts` is then mapped as before
1. Login as a volunteer (sistering+volunteer1@uwblueprint.org would work)
2. Navigate to the "My Shifts" tab
3. Click the Requests Pending Confirmation tab, and ensure there are no duplicate postings (i.e. no duplicate "Croissant Making" shifts)
* My approach (from what I can tell) is slightly different than what was outlined for me in the ticket, under Technical. I didn't think it was necessary to create any new …
> Deduplicate postings in requests pending table

- frontend/src/components/pages/Default.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
- frontend/src/components/volunteer/EmptyPostingCard.tsx
- frontend/src/components/volunteer/PostingCard.tsx
- frontend/src/types/PostingTypes.ts
- frontend/src/utils/DateTimeUtils.ts
Closes #254
- Add new conditions for regular vs event posting cards
- Add logic to render time range for event posting based on all children 
Regular
Event
NOTE: An event posting is a posting whose start/end date are the same (EDT time)
1. Add an event and regular posting that is visible on browse posting page
2. Go to `volunteer/postings`
3. Ensure that you can see the event card with specific date and specified time range
4. Ensure that you can see the regular posting card with date range and no specific time range on the card instead saying "See posting details"
* Correctness and cleaniness
> Add conditions to render event vs regular postings on postin cards

- frontend/src/components/user/AccountForm.tsx
- frontend/src/types/api/SkillTypes.ts
- frontend/src/types/api/UserType.ts
Closes #412 
* Added GraphQL query for skills in `AccountForm.tsx` for account creation page
* Created `LANGUAGES` array in `UserType.ts` and `Language` string union type
* Imported `LANGUAGES` in `AccountForm.tsx` 
1. Go to `http://localhost:3000/new-account` to see the account creation page
2. Check the skills are being queried (currently no form field for languages)
> Query skills and create languages array used for account creation page

- backend/graphql/types/postingType.ts
- backend/prisma/migrations/20220620220742_remove_archive_state_from_posting/migration.sql
- backend/prisma/schema.prisma
- backend/types.ts
- frontend/package.json
- frontend/src/components/admin/AdminPostingCard.tsx
- frontend/src/components/pages/Default.tsx
- frontend/src/components/volunteer/PostingCard.tsx
- frontend/src/types/PostingTypes.ts
- frontend/src/types/api/PostingTypes.ts
- frontend/src/utils/DateTimeUtils.ts
- frontend/yarn.lock
Closes #343 
Closes #344 
* Implemented the Admin / Super Admin posting cards
* Rendering depends on the Posting's states, see [Figma](https://www.figma.com/file/TWJTNWjK75A6VgSisySTLe/Sistering-%2F-Admin-Experience?node-id=1420%3A39607)
* Backend posting status doesn't correspond with frontend, so they are resolved as discussed w/ Rickson. See getPostingStatus() method for details.
* Preview:
1. Navigate to http://localhost:3000/ with an admin account (this should also work for employees, but backend currently unauthorizes employees to retrieve postings).
2. Check that the cards render according to designs. Can try adding more postings with different statuses.
* Correctness of rendering / matches designs
> Admin homepage posting card

- backend/graphql/resolvers/userResolvers.ts
- backend/graphql/types/userType.ts
- backend/prisma/migrations/20220710175708_user_invite_better_field_name_unique_email/migration.sql
- backend/prisma/schema.prisma
- backend/services/implementations/userService.ts
- backend/services/interfaces/userService.ts
- backend/types.ts
Closes #439 
* Created resolver that handles deletion of userInvite row based on unique email (follow up migration)
* Added necessary type for resolver
1. Create an existing user invite shown here: https://github.com/uwblueprint/sistering/pull/470
2. delete the user invite record using the invitee's email
```
mutation {
createUserInvite(email: "test4@gmail.com", role: VOLUNTEER) {
uuid
}
}
mutation {
deleteUserInvite(email:"test4@gmail.com") {
uuid
}
}
```
* correctness and cleanniness
> Add resolver and types for delete user invite

- backend/constants/emailTemplates.ts
- backend/services/implementations/authService.ts
- backend/utilities/templateUtils.ts
Closes #483
* Add templates
* Use it for reset-password email as an example
1. Run this app locally since backend changes is not in preview
2. Click reset password and ensure the email as designed
* Look and feel
* Code cleanliness
> Add email template utils

- backend/prisma/seed.ts
- frontend/src/components/admin/schedule/AdminScheduleVolunteerRow.tsx
- frontend/src/components/admin/schedule/AdminScheduleVolunteerTable.tsx
- frontend/src/components/admin/schedule/ScheduleSidePanel.tsx
- frontend/src/components/admin/schedule/volunteersidepanel/NoVolunteerShiftsRow.tsx
- frontend/src/components/admin/schedule/volunteersidepanel/VolunteerNameHeader.tsx
- frontend/src/components/admin/schedule/volunteersidepanel/VolunteerShiftsRow.tsx
- frontend/src/components/admin/schedule/volunteersidepanel/VolunteerShiftsTable.tsx
- frontend/src/components/admin/schedule/volunteersidepanel/VolunteerSidePanel.tsx
- frontend/src/components/admin/schedule/volunteersidepanel/VolunteerSkillsSection.tsx
- frontend/src/components/pages/admin/schedule/NoShiftsPanel.tsx
- frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
- frontend/src/types/api/ShiftSignupTypes.ts
- frontend/src/utils/DateTimeUtils.ts
Closes #505 
* Created the volunteer profile side bar
* Used `volunteerUserById` and `getShiftSignupsForUser` queries to get all the info needed
With local repo seed:
1. Navigate to `.../admin/schedule/posting/1` (or /2), click on a shift that has available volunteers, and then click the profile icon of a volunteer
2. Ensure the site doesn't crash, and navigate between volunteers and shifts (the side panel should either display volunteer profiles or shift information)
* Review implementation logic
* Review empty state design implementations (i.e. when there are no skills listed, or no shifts of a certain type)
> Create Volunteer Profile Side Panel

- backend/graphql/types/userType.ts
- backend/prisma/migrations/20220731144814_made_do_b_and_pronouns_part_of_user/migration.sql
- backend/prisma/schema.prisma
- backend/prisma/seed.ts
- backend/services/implementations/__tests__/userService.test.ts
- backend/services/implementations/userService.ts
- backend/types.ts
- frontend/src/components/pages/EditAccountPage.tsx
- frontend/src/components/user/AccountForm.tsx
- frontend/src/types/api/EmployeeTypes.ts
- frontend/src/types/api/UserType.ts
Closes #503
* Changed prisma schema, changed corresponding types in backend and frontend, as well as to graphql schemas.
* 
1. Use any query with users and they will now have pronouns and date of birth associated with them.
As a general note: I noticed that, while the prisma schema originally made pronouns essential and dateOfBirth nullable, the typing in types didnt reflect that (sometimes both were nullable). How important is it that the type `string` vs `string | null`?
> Migrate DoB and pronouns to user model

- frontend/src/components/admin/AdminPostingCard.tsx
- frontend/src/components/pages/admin/AdminHomepage.tsx
- frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
Closes #552
* Add missing posting details link to admin posting card by linking to appropriate existing page via `history.push`
1. As a admin, I can click on any posting card under any tab in admin homepage (`/admin`) to view its posting details
* Any regressions
* Code cleanliness
> Add missing posting detail links to admin posting cards

- frontend/src/components/admin/AdminHomepageHeader.tsx
- frontend/src/components/pages/admin/AdminHomepage.tsx
- frontend/src/reducers/PostingContextReducer.ts
- frontend/src/types/PostingContextTypes.ts
Closes #564
* New `ADMIN_POSTING_RESET` reducer action for resetting posting context to default state
* Dispatches this action before beginning a new create or edit posting flow (i.e. before navigating to the create or edit pages from the admin home page)
Note: This addresses a more general case of the issue vs just clearing after saving to the backend. The posting context is modified before the save so we would still see leftover fields from the context if beginning a new create/edit after previously abandoning a create/edit part way through.
1. Use the preview deploy link and sign in as an admin
2. Create a new posting from the admin home page
3. Try to create another posting and verify that the form and posting context contain the default fields (can use React dev tools)
4. Open a …
> Clear posting context before visiting new create or edit posting pages

- frontend/src/components/pages/EditAccountPage.tsx
- frontend/src/components/user/AccountForm.tsx
Closes #559
* Apply `getTitleCaseForOneWord` util function to languages in the account form
1. Login as an admin
2. Create a user invite (either admin or volunteer)
3. Accept user invite and fill in fields in create account form, verify that the language options have the proper casing
4. Login as the new user and go to the edit account page (note: due to issue mentioned in #560 the languages selected at account creation were not persisted). Again, verify that the language options have proper casing
5. Save the edits and reload the edit account page to ensure that languages have persisted and that they are displayed with proper casing
* Correctness
> Use title case for languages in create/edit account form

- frontend/src/components/admin/users/ProfileDrawer.tsx
Closes #540
* Remove unused button in user management profile drawer reset password button
1. Go to `admin/users` route in preview, ensure that the reset password button is no longer visible
No regression
> Remove unused admin reset user password button

- frontend/src/components/common/SignupNavbar.tsx
- frontend/src/components/pages/EditAccountPage.tsx
Closes #573 
Closes #533 
* Made logo clickable in the `SignupNavbar.tsx` component
* Customized navbar for `/edit-account` per user type
1. Navigate to `/edit-account` as multiple roles to see if navbar changes 
2. Go to `/new-account` and check if logo expands + clicks!
> Add clickable logo on signup nav and customize tabs on edit-account ✨ 

- backend/services/implementations/shiftService.ts
- frontend/src/components/admin/ShiftCalendar/WeekViewShiftCalendar.tsx
Closes #567 
* Remove week view shift calendar valid start range guard (use backend to do appropriate filtering to support uneven shift schedules)
* Updated shift service to filter out shifts outside of start range last after building all-time blocks from chosen recurrence to support uneven shifts
1. As a super admin, I should be able to create a posting with an uneven schedule. eg: a posting that starts this week Tuesday, and has weekly shifts from Monday to Friday at 3 -> First week should have only 4 shifts, second week forward should have 5 shifts including the one on Monday, etc...
2. As a super admin, go the posting review page and confirm the uneven schedule has been created
* Correctness/edge cases
> Remove shift creation start date guard for backend handling

- backend/graphql/index.ts
- backend/graphql/resolvers/postingResolvers.ts
- backend/graphql/resolvers/shiftResolvers.ts
- backend/graphql/types/shiftType.ts
- backend/services/implementations/postingService.ts
- backend/services/implementations/shiftService.ts
- backend/services/interfaces/shiftService.ts
- frontend/src/App.tsx
- frontend/src/components/admin/AdminHomepageHeader.tsx
- frontend/src/components/admin/ShiftCalendar/MonthViewShiftCalendar.tsx
- frontend/src/components/admin/calendar/OrgWideCalendar.tsx
- frontend/src/constants/Routes.ts
- frontend/src/types/api/ShiftTypes.ts
Closes #535 
Closes #555 
* Added a new query `shiftsWithSignupsAndVolunteers` (of the shiftService) to return all posting's shifts with signups and volunteers.
* Created the org wide calendar page at `/admin/calendar`. This calendar displays the **scheduled/past** signups and volunteers from all postings across Sistering.
* Some clean-up work
* Renamed IShiftService.ts to shiftService.ts on the backend to keep interface file naming convention.
* Re-ordered routes for better organization
* Extended `getUserBranchesByUserId` functionality to also work for employees and admins (this is used in `getPostings`, which is then called in the frontend for employees and admins)
1. Navigate to [](http://localhost:3000/admin/calendar) as a super admin, should see all scheduled and past postings in …
> Implement Organization-Wide Calendar for Admins & Employees

- frontend/src/App.tsx
- frontend/src/index.tsx
Closes #513 
* Added `UseEffect` in `App.tsx` to refresh pages automatically if Access Token expires
1. Go to Network tab on the Console Inspect
2. he first 200 GraphQL response and on `Headers` you should see a refresh token. Copy that.
3. Refresh the page
4.  Navigate to at 200 GraphQL response again and the refresh token should be the same as the access token.
> Remove backend logout call on refresh failure and reload window

- frontend/src/components/common/RichText/RichTextField.tsx
Closes #565
* Changed width of the textbox container from `container.md` to `100%`.
1. Login as an admin (sistering+admin@uwblueprint.org works) and create a posting, verifying that the Role Description text box extends the entire way like the Figma design: 
* We could pass width in as a prop for different uses but I don't think it's necessary, this is the only place we use the `RichTextField` component.
> Change textbox width

- frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
- frontend/src/components/admin/calendar/OrgWideCalendar.tsx
- frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
- frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
- frontend/src/theme/index.ts
Closes #537 
* Added an unavailable shifts tab to the volunteer shifts table. A shift is unavailable if the super admin published the schedule and volunteer was not selected for that shift.
* Fixed some bugs on OrgWideCalendar & schedule creation toast
* Fixed table UI for volunteer shifts table
1. Create some cancelled shifts w/ prisma studio
2. Test that these shifts are correctly displayed in the filled shifts tab
* Functionality
> Add unavailable shifts tab to volunteer shifts table

- frontend/src/components/pages/EditAccountPage.tsx
Closes #599 
* Added user branch tags to the edit profile page
* Fixed existing React warning with invalid date format
1. Navigate to `http://localhost:3000/edit-account`, the user's branches should show at the top:
* N/A
> Add branch tags to edit profile page

- backend/services/implementations/branchService.ts
- frontend/src/components/admin/users/ProfileDrawer.tsx
- frontend/src/components/admin/users/UserManagementTableProfileCell.tsx
- frontend/src/components/pages/admin/user/MultiBranchSelector.tsx
Closes #569
* Updated updateUserBranchByEmail mutation such that it deletes stale signups when a volunteer has been removed from the branch
* Fix bug where selected branch state is in consistent when discarding branch edits on user management profile drawer at `admin/users` by resetting selected branches to user branches on closing drawer
1. got to `admin/users`, when saving volunteer branches on the profile drawer, a new modal appears for the destructive action
2. when removing a branch from user, ensure that all signups for that user regardless of status has been removed
3. If you discard your branch edits the state is now consistent when revisiting the profile drawer
* Correctness
* Look and feel
> Update branch mutation query to remove stale signups + unsaved selected branches bug

- backend/services/implementations/postingService.ts
- backend/services/implementations/shiftSignupService.ts
- backend/utilities/dateUtils.ts
Closes #604 
* Update getShiftSignupsForUser query to only query for signups for postings that have not ended yet. We do not have any usage of this query that needs expired signups.
1. Do this locally where you have direct access to change the DB records
2. Login as a volunteer
3. Sign up for 3 signups
4. Go to DB and put signup for PUBLISHED, CANCELLED, and PENDING, one for each. They should appear in volunteer homepage signups tab
5. GO to DB and put posting endate to a date in the past
6. The signups for volunteer should no longer be visible
7. Similarly they should not be visible on schedule review page - volunteer profile page
*
> Update getShiftSignupForUser to only return signups for current postings

- frontend/src/utils/DateTimeUtils.ts
N/A - quick fix for this issue:
* Interpret date in UTC instead of local time in `formatDateMonthDay` util function used in `VolunteerPendingShiftsTableRow`
1. Login as a volunteer who has pending shifts
2. Verify that the displayed deadline date of the pending shift's associated posting matches what is returned by the backend
* N/A
> Fix timezone bug in VolunteerPendingShiftsTableRow

- frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
Closes #603 
* Added condition in `handleOnPublishClick()` method in `SchedulePostingPage.tsx` to also set `PENDING` signups to `CANCELED`. 
1. As a volunteer, signup for a posting
2. As an admin, review signups for that posting and do not check the volunteer signup
3. Publish the posting
4. Check that the volunteer signup was cancelled
> Set unselected signups to cancelled on posting publish

- frontend/src/components/admin/BranchManagerTable.tsx
- frontend/src/components/admin/LanguageManagerTable.tsx
- frontend/src/components/admin/SkillsManagerTable.tsx
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/ResetPassword.tsx
- frontend/src/components/common/Loading.tsx
- frontend/src/components/pages/AccountCreatedPage.tsx
- frontend/src/components/pages/CreateAccountPage.tsx
- frontend/src/components/pages/NotFound.tsx
- frontend/src/components/pages/admin/AdminHomepage.tsx
- frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
- frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
- frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
- frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
- frontend/src/components/volunteer/shifts/VolunteerShiftsTableEmptyState.tsx
…on settings manager tables
Closes #625 
* Reworded pending shifts tab from `Requests Pending Confirmation` to `Pending Shifts`
* Fixed shifts table heights to be consistent and background colour of volunteer shifts page to remain `background.light`
* Fixed bottomBorder of last row in settings manager table to be none
1. Go to `http://localhost:3000/volunteer/shifts`
2. Check that table name was reworded
3. Signup for a shift, approve or cancel shift, check that table heights are the same across all shift tables
> Reword Volunteer Shifts Tab to be Less Vague + UI underflow

- frontend/src/components/pages/CreateAccountPage.tsx
Closes #632
* Fixed continue link to be attached to button instead of text on create-account page
1. Go to `http://localhost:3000/create-account`
2. Check that the continue button can be clicked without cursor on text
> Fix create-account page continue link attach to button

- frontend/src/components/admin/ShiftCalendar/WeekViewShiftCalendar.tsx
- frontend/src/components/admin/posting/PostingFormShifts.tsx
Closes #614 
* Enhancing the logic I removed in https://github.com/uwblueprint/sistering/pull/578/files#diff-1419dbfb9a8576e06b1e14356bb91202a213dcc954255f30c3019d8b0a7a9c96L128
* we should only specify valid start for non-recurring schedules or schedules with start/end date in the same week. This basic guard is sufficient although it does not consider more specific cases like 2 week posting for 1 month recurring event (which actually should have a start guard)
1. As a super admin, login and go to create new posting page
2. You should not be able to select shifts on days before the start date (we still allow it for recurring events lasting over than 1 week to allow uneven schedules) 
* Correctness
> Update weekly calendar view to restrict invalid start

- frontend/src/components/admin/BranchManagerTable.tsx
Closes #575 
- Update toast msg description to be static - usually when a user fails to delete a toast, it is because there are existing postings that is still using the branch, the error tells the user to clear those references before proceeding to delete a branch
1. Log in as super admin, try to delete a branch that is used by a toast, you should see the toast error in the screen shot
2. Try creating a new branch and assign yourself to that branch, you should still be able to delete that branch without any error toast
* Any scenarios where this toast error would not make sense - this solution is a tradeoff for simplicity. I can't really see any other internal error scenarios that would cause this issue atm.
> Update better toast msg of delete branch failure toast

- backend/graphql/resolvers/branchResolvers.ts
- backend/graphql/resolvers/postingResolvers.ts
- backend/graphql/types/postingType.ts
- backend/services/implementations/branchService.ts
- backend/services/implementations/postingService.ts
- backend/services/interfaces/branchService.ts
- backend/services/interfaces/postingService.ts
- backend/utilities/dateUtils.ts
- frontend/src/components/admin/calendar/OrgWideCalendar.tsx
- frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
- frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
- frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
Closes #647 
* Filter by user branches in `postings` resolver if user is volunteer or employee
* If employee also only return scheduled or past postings
* If volunteer also only return unscheduled or scheduled postings
* Removed old way of doing this for volunteers where we pass an optional userId parameter
* Updated `VolunteerPostingsAvailabilities` page to redirect to not found page on posting error
* Updated `SchedulePostingsPage` to redirect to not found page on posting error
* Updated `branches` query only returns branches that user is in
1. Log in as employee
2. Check that you can only see postings of branches you are in
3. Log in as volunteer, and check that you can also only see postings of branches you are in
> Fix employees can see postings outside of branch

- backend/graphql/index.ts
- frontend/src/components/user/AccountForm.tsx
- frontend/src/components/user/fields/SearchSelectorField.tsx
Closes #591, #666
* Replaced SelectorField with SearchSelectorField for languages in the AccountForm, and added all necessary dependencies, very similar to the skills SearchSelectorField implementation
1. Login as a volunteer or employee
2. Navigate to the Edit Profile page and test the languages field
3. Note: You won't be able to actually submit the changes if using the Firebase hosting link below since that does not include the backend changes in the preview. Testing locally works fine.
* Correctness
* Similarity with the SearchSelectorField for adding skills
* Ensuring all code for the languages field implementation doesn't still say "skills" anywhere
> Update languages field to use SearchSelectorField
