backend/package.json
backend/prisma/schema.prisma
backend/server.ts
backend/yarn.lock

Closes #12
* Installed prisma dependencies
* Added autogenerated `prisma.schema` file
1. Add the test model to `backend/prisma/schema.prisma`
```js
model Test {
id      Int      @id @default(autoincrement())
name    String
}
```
In the `backend/prisma/.env` file, add this line:
```
DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:5432/${POSTGRES_DB}"
```
2. Add the following to `backend/server.ts`
```js
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
async function main() {
await prisma.$connect();
console.log("Successfully connected to DB using Prisma!");
}
main()
.catch((e) => {
// e should be a PrismaClientInitializationError if connection fails
console.error("Error connecting to DB using Prisma!");
throw e;
})
.finally(async …
```

Migrate database connection logic from Sequelize to Prisma

---

backend/graphql/index.ts
backend/graphql/resolvers/skillResolvers.ts
backend/graphql/types/skillType.ts
backend/prisma/migrations/20211102231132_add_skills_unique_constraint/migration.sql
backend/prisma/schema.prisma
backend/services/implementations/skillService.ts
backend/services/interfaces/ISkillService.ts
backend/types.ts

Closes #44
* Defined `SkillDTO` types
* Created `SkillService` with CRUD methods and GraphQL resolvers
* Added a unique constraint on skill name
1. Start docker and `run docker-compose up --build`
2. Run `docker exec -it sistering-backend-1 /bin/bash -c "npx prisma generate"` to update the prisma client library
3. Go to http://localhost:5000/graphql
4. Verify all the GraphQL queries and mutations related to the Prerequisite Model are working as expected
* Functional GraphQL queries & mutations

Skills crud resolvers

---

backend/graphql/index.ts
backend/graphql/resolvers/branchResolvers.ts
backend/graphql/types/branchType.ts
backend/graphql/types/postingType.ts
backend/graphql/types/skillType.ts
backend/prisma/migrations/20211218191340_make_branch_name_unique/migration.sql
backend/prisma/schema.prisma
backend/services/implementations/branchService.ts
backend/services/interfaces/branchService.ts
backend/types.ts

Closes #79
- Defined `BranchRequestDTO` and `BranchResponseDTO` types
- Implemented CRUD methods in `BranchService`:
- getBranch
- getBranches
- createBranch
- updateBranch
- deleteBranch
- Create corresponding GraphQL resolvers and DTOs
- Added a unique constraint on branch name and generated associated prisma migration file
1. Start docker and `run docker-compose up --build`
2. Run `docker exec -it sistering-backend-1 /bin/bash -c "npx prisma generate"` to update the prisma client library
3. Go to http://localhost:5000/graphql
4. Verify all the Branch GraphQL queries and mutations are working as expected
* Functional GraphQL queries & mutations

Create Branch CRUD Methods and GraphQL Resolvers 

---

frontend/src/App.tsx
frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
frontend/src/constants/Routes.ts

Closes #89 
* Created a new React component called VolunteerPostingsPage with the route `/volunteer/postings` 
1. `docker-compose up --build`
2. Navigate to http://localhost:3000/volunteer/postings and verify that the page consists of a heading that says "Volunteer Postings"
* Ensuring http://localhost:3000/volunteer/postings exists

Create Volunteer Posting List Page

---

backend/graphql/index.ts
backend/graphql/types/postingType.ts
backend/graphql/types/shiftType.ts
backend/package.json
backend/services/implementations/postingService.ts
backend/services/implementations/shiftService.ts
backend/types.ts
backend/yarn.lock

Closes #91 
* Added a `DateTime` GQL scalar type for handling dates in the format of "YYYY-MM-DD HH:mm"
* Updated existing Typescript variables to use the `Date` type instead of string
* Updated existing implementations of `Shift` and `Posting` services (and also removed string/date validations and conversions in these services). Updated instances of moment operations with built in JS
* Removed moment npm package as it is no longer needed.
1. docker compose up
2. Verify that postings and shifts operations are working as expected
Example queries:
`mutation {
createPosting(posting: {
branchId: 4
skills: [1]
employees: [1]
title: "test posting"
type: INDIVIDUAL
description: "test description"
startDate: "2022-01-20"
endDate: "2022-01-20"
autoClosingDate: "2022-01-20"
numVolunteers: 10
}) { …

Use scalar Date & DateTime instead of strings in handling Postings & Shifts

---

frontend/src/App.tsx
frontend/src/components/pages/Default.tsx
frontend/src/components/pages/EditPostingPage.tsx
frontend/src/constants/Routes.ts
frontend/src/contexts/admin/PostingContext.ts
frontend/src/contexts/admin/PostingContextDispatcherContext.ts
frontend/src/reducers/PostingContextReducer.ts
frontend/src/types/PostingContextTypes.ts
frontend/src/types/PostingTypes.ts

Partially addresses #57, #58, #102, #59
* Added context for posting info
* Created example of how to write to and read from global posting state (this can be deleted after implementing the actual create posting UI)
1. Run the application locally (staging backend has issues right now so cannot use deployment preview link)
```bash
docker-compose up --build
```
2. Log in and click on "Edit Posting" on the default page
3. Enter some information in the form, then verify the changes on the default page (default page is accessing data from global state). Try jumping back and forth between these pages and manipulating the data. **Note that you should not reload the app as that will clear the app state**. This means you should not refresh or navigate by manually changing the URL, instead, navigate …

Create context components for posting state management

---

frontend/src/theme/index.ts

Closes #114 
* Add default styling for the following: heading, body, and chakra components (tabs, tag, button)
1. Go to page, login, inspect text styles of heading, body text, tabs, tags, and button.
* Font usage is correct

Add default fonts for components

---

frontend/src/theme/index.ts
frontend/src/theme/textStyles.ts

Closes #141 
* Created `textStyles.ts` under `src/theme` which exports `textStyles` object used in `index.ts`
* Changed Tag base style to use `textStyles.caption`
1. Scroll down to the design system in the default page
2. Verify that the tags use the caption text style
* Correct use of text styles

Apply "caption" text style to tags

---

frontend/package.json
frontend/src/components/admin/posting/CreatePostingShifts.tsx
frontend/src/components/pages/Default.tsx
frontend/src/components/pages/admin/posting/CreatePostingShiftsPage.tsx
frontend/src/constants/Copy.ts
frontend/yarn.lock

Closes #58
* Create form component to allow admins to create posting shifts 
1. Run the application locally or use the preview link below
2. Log in and click on the "Create Shifts" tab on the default page 
3. Fill in the fields and test that the field errors work as expected (no empty fields, and start date should not be later than end date)
4. Verify that the data is being reflected in the global context by going back to the default page (using the "Go Back" button) and checking the start date, end date, and recurrence intervals match what you inputed
* Does the context work correctly?
* Do the field validations work as expected?

Admin Create Posting Shifts Page UI

---

backend/prisma/seed.ts

Closes #193
* Added rich text descriptions to the seed data postings 
1. Go to the postings page at `/volunteer/postings`
2. Go to a posting details page `/volunteer/posting/1`
* Check that the postings are still being rendered in general. The description does not have to be formatted properly.

Add rich text to seed data

---

frontend/src/components/volunteer/VolunteerNavbar.tsx

Closes #184 
* Fetched user name using `AuthContext`
* Created `userName` variable to display in navbar
1. Go to `/volunteer/shifts` or `/volunteer/postings` route where the volunteer navbar is mounted
2. Check that the navbar shows the name of the logged in user

Fetch and display user name in volunteer navbar

---

backend/graphql/index.ts
backend/graphql/resolvers/shiftResolvers.ts
backend/graphql/types/shiftType.ts
backend/services/implementations/shiftService.ts
backend/services/interfaces/IShiftService.ts
frontend/src/App.tsx
frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
frontend/src/components/volunteer/shifts/VolunteerAvailabilityTableRow.tsx
frontend/src/constants/Routes.ts
frontend/src/theme/index.ts
frontend/src/types/api/SignupTypes.ts
frontend/src/utils/DateTimeUtils.ts

Closes #119 
https://user-images.githubusercontent.com/44826218/157791442-8777a160-2f9c-4765-b562-1310a45250f4.mp4
* Add header to allow moving between weeks
* Added dropdown to allow moving between weeks of start and end range
NOTE: State management of shifts not saved yet
1. Ensure that jumping from dropdown works
2. Ensure that moving to prev/next week works
3. cannot move beyond start/end weeks
*

volunteer select availability table headers

---

backend/graphql/index.ts
backend/graphql/types/shiftSignupType.ts
backend/services/implementations/shiftSignupService.ts
backend/types.ts

Doesn't close a ticket, but required for #127 
* Updated the endpoints for shiftSignup service to include posting fields 
1. Run the docker container 
2. Go to GraphQL playground and verify that the posting details (id, title, and autoClosingDate) are returned as expected
* Code cleanliness and functionality

Add posting fields to shiftSignup fetch

---

frontend/src/components/admin/schedule/AdminSchedulePageHeader.tsx

Closes #180 
* Create `AdminSchedulePageHeader.tsx` component in `frontend\src\components\admin\schedule` that takes `branchName` as a prop
* Temporarily set the back link to `/` (default page) and mounted component in default page
1. Go to the default page where the header is mounted
2. Check header functionality and design

Schedule creation page header

---

frontend/src/components/pages/admin/schedule/NoShiftsPanel.tsx
frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
frontend/src/constants/Copy.ts

Closes #171 
* Created `NoShiftsPanel` under `frontend/src/components/admin/schedule`
* Add the copy to `/constants/Copy.ts`
1. Go to `/volunteer/shifts` where the component is temporarily mounted on
2. Check that the component looks good
* Component follows designs

No shifts panel

---

frontend/src/components/admin/schedule/ShiftTimeHeader.tsx
frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx

Closes #173 
* Created `ShiftTimeHeader.tsx` component in `frontend\src\components\admin\schedule`
* The header accepts two props:
*  Array of shift times
* `onDateSelected` function called when select option is changed
1. Go to `/volunteer/shifts` where the component is temporarily mounted on
2. The `onDateSelected` method currently just console logs the selected value. Check that the correct values are being logged.
* Component follows designs

Edit volunteers shift time header

---

frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
frontend/src/components/common/RichText/RichTextDisplay.tsx
frontend/src/components/common/RichText/RichTextField.tsx
frontend/src/components/common/RichText/fontSizeObject.ts

extension of #131 
* allows the richText display component to handle different font sizes
* created a common font-size css object used between RichTextDisplay.tsx and RichTextField.tsx
- add the following description to a posting detail
{"blocks":[{"key":"amcul","text":"jawofej","type":"header-one","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"e1guq","text":"awjofijwioefj","type":"unordered-list-item","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"3vgfa","text":"asdfjlasjdlk","type":"unordered-list-item","depth":0,"inlineStyleRanges":[{"offset":0,"length":12,"style":"BOLD"}],"entityRanges":[],"data":{}},{"key":"fff6u","text":"asdfasdfasd","type":"header-three","depth":0,"inlineStyleRanges":[{"offset":0,"length":11,"style":"ITALIC"}],"entityRan …

Allow RichTextDisplay to handle font-sizes

---

backend/graphql/types/postingType.ts
backend/graphql/types/userType.ts
backend/prisma/migrations/20220408003859_update/migration.sql
backend/prisma/schema.prisma
backend/prisma/seed.ts
backend/services/implementations/postingService.ts
backend/services/implementations/userService.ts
backend/types.ts
frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
frontend/src/components/admin/posting/CreatePostingReview.tsx
frontend/src/types/api/EmployeeTypes.ts

Closes #245 
* Augmented Employee model with title field, and relevant backend methods to read/write this field
1. Run docker exec -it sistering_backend bash -c "npx prisma db seed"
2. navigate to http://localhost:3000/admin/posting/create/basic-info, go through the forms and select "Edna Employee" as the point of contact
3. on the 3rd form (review and post), ensure the employee card displays the following: 
*  the modified backend methods are able to correctly read/write the title field

Augment Employee Model

---

frontend/src/components/admin/SaveVolunteerModal.tsx

… modal
Closes #174
* Created a modal for saving volunteers using `RemoveVolunteerModal` as a template
* Small style change to `RemoveVolunteerModal` to be more in line with mocks
* Added a void onclick function for close button in top right of `SaveVolunteerModal`
1. Add `<SaveVolunteerModal onClose={() => {}} isOpen />` to any page. For example, `Default.tsx`
2. Check to see if the modal looks as expected.
* If the styling matches the mocks.

Save Volunteer Modal

---

backend/graphql/index.ts
backend/graphql/resolvers/postingResolvers.ts
backend/graphql/types/postingType.ts
backend/services/implementations/postingService.ts
backend/services/interfaces/postingService.ts
frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx

Closes #256
* Modified the postings query to accept 3 optional parameters
* Modified `VolunteerPostingsPage` query to pass in 3 parameters
* Updated postings query to be authorized by volunteers
1. `docker-compose up`
2. Testing backend: run the following graphql commands and verify the output is as expected
```graphql
mutation {
createVolunteerUser(
volunteerUser: {
firstName: "Albert"
lastName: "Lai"
dateOfBirth: "2003-01-02"
email: "INSERT_RANDOM_EMAIL_HERE"
password: "lollol"
hireDate: "2022-04-18"
skills: [1],
branches: [1]
}
){
id
}
}
mutation {
login(
email: "INSERT_RANDOM_EMAIL_HERE"
password: "lollol"
) {
accessToken
}
}
query {
postings {
id
title
autoClosingDate
status
branch {
id
}
}
}
query {
postings(
closingDate: "2022-03-01"
statuses: [PUBLISHED, DRAFT]
userId: "4"
) {
id …
```

Add Optional Query Parameters to Postings Query

---

frontend/src/App.tsx
frontend/src/components/admin/schedule/AdminPostingScheduleHeader.tsx
frontend/src/components/pages/admin/schedule/AdminSchedulePostingReviewPage.tsx
frontend/src/constants/Routes.ts

Closes #179
* Created the heading according to the mocks
1. Add the component to `Default.tsx`. For example, I used the following snippet to test: 
```      
<Flex width="100%" justifyContent="center">
<Box width="90%">
<AdminPostingScheduleHeader postingName="test" postingID={0} />
</Box>
</Flex>
```
* Whether the button functionality works as expected
* Whether the component looks like the mocks

Admin Posting Schedule Header

---

frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
frontend/src/components/admin/schedule/AdminPostingScheduleHeader.tsx
frontend/src/components/admin/schedule/AdminSchedulePageHeader.tsx
frontend/src/components/admin/schedule/AdminScheduleTable.tsx
frontend/src/components/admin/schedule/AdminScheduleTableRow.tsx
frontend/src/components/admin/schedule/ShiftTimeHeader.tsx
frontend/src/components/common/Navbar.tsx
frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
frontend/src/constants/Routes.ts
frontend/src/constants/Tabs.ts
frontend/src/constants/Volunteer.ts

Closes #220  and the ticket for the UI layout of the admin scheduling page
* Created a generic navbar component that is reused between the volunteer navbar and admin navbar
* Fiddled with the margin/padding/border values to get the layout aligned. The aspect ratio between the side panel and the rest of the page seems off, even though designs say width=400px. BTW the actual side panel component is still in a pr.
* I haven't figured out how to fit the entire calendar to the page without scrolling yet
Layout: 
1. Go to `http://localhost:3000/admin/schedule/posting/1` and check that the layout matches [designs](https://www.figma.com/file/TWJTNWjK75A6VgSisySTLe/Sistering-%2F-Admin-Experience?node-id=888%3A18932)
Navbar 
1. For the admin navbar go to …

Set up admin schedule layout

---

frontend/src/components/auth/Login.tsx
frontend/src/components/auth/ResetPassword.tsx
frontend/src/components/common/ErrorModal.tsx
frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
frontend/src/components/pages/admin/schedule/AdminSchedulePostingReviewPage.tsx
frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx

Closes #234 
* Created `ErrorModal.tsx` component under `/src/components/common`
* Added component to all the pages we will be using that require a GraphQL query or mutation
1. To directly see component, you go to any of the pages where it's mounter and remove the `error` condition

Error modal

---

frontend/package.json
frontend/src/components/admin/schedule/AdminScheduleVolunteerRow.tsx
frontend/src/components/admin/schedule/AdminScheduleVolunteerTable.tsx
frontend/src/components/admin/schedule/ScheduleSidePanel.tsx
frontend/src/components/admin/schedule/ShiftTimeHeader.tsx
frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
frontend/src/components/pages/admin/schedule/testData.ts
frontend/yarn.lock

Closes #176 
* Created `ScheduleSidePanel.tsx` under `/components/admin/schedule`
* If there are no shifts, the side panel displays no shifts panel
* If there are shifts, the side panel displays shift time header (#173) and admin schedule table (#172)
* Created sample data for testing in `testData.ts` that mimics the response data from backend
1. Go to `/admin/schedule/posting/1` where the side panel is mounted
2. Test that everything works as expected
3. Try changing the shifts to be an empty array to check that no shifts panel is displayed

Side panel

---

backend/graphql/types/postingType.ts
backend/services/implementations/postingService.ts
backend/types.ts
frontend/src/components/common/PostingDetails.tsx
frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
frontend/src/types/api/EmployeeTypes.ts
frontend/src/types/api/PostingTypes.ts

Closes #248 
* Update the getPosting method in the postingService to return employee's name, email, phone number
* Fetch the employee information and display in the POC card for in the PostingDetails component
1. Navigate to http://localhost:3000/volunteer/posting/1 as an admin, verify the points of contact displays the Edna test employee card
* the postingService functions work as intended with the new changes
* the PostingDetails component fetches the correct data and displays it correctly

Include Employee Info in POC Card

---

frontend/src/components/admin/schedule/AdminScheduleTable.tsx
frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx

Closes #157
* Add header similar to the one in select availability table
* Add start/end date component param to table for posting select week range
* Add required buttons w/o functionality TODO later: add appropriate calls
1. Go to route `/admin/schedule/posting/1`
2. Back/publish buttons are in place
3. Title of table in place (hard coded atm)
4. Header with week select filter in place
* Correctness
* If there is a better filter for week select logic

Add header to schedule review table

---

frontend/src/components/auth/Login.tsx

* This removes the UI for google login
1. Go to `/` while logged out and check that the login with Google button is not there.
*  The UI should be gone

Remove google login UI

---

frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
frontend/src/components/admin/posting/CreatePostingShifts.tsx

Closes #283 
* Changed error state boolean variables to strings that contains the error message
* Validate that selected dates are not in the past in the `handleNext()` functions
1. Use the preview deploy link to test if the dates in past case is being correctly validated
General code correctness.
**Known caveat:** the new and longer error messages are surfacing a layout bug. Unfortunately I don't have the capacity to address this right now.

Validate against past dates in create posting form

---

frontend/src/components/common/PostingDetails.tsx
frontend/src/components/volunteer/PostingCard.tsx

N/A, small fixes.
* Fixing issue where div tag is inside p tag
* Fix issues where key is not unique for list of rendered React components
1. Go to pages with changed components
2. Ensure that console log has no warnings

Resolve console warning on volunteer scheduling pages

---

frontend/src/components/common/Navbar.tsx

Closes #288 
* Port the logout functionality from `Logout.tsx` to our `Navbar` logout button
1. Go to volunteer posting page and admin schedule posting page
2. Make sure that log out button actually logs the user out.
As far as I'm aware, checking logging out should just remove the token from the local storage in the browser.
* Make sure that logout functionality works

Add Logout Functionality to Navbar

---

frontend/src/components/pages/Default.tsx

Cleanup default page for admin

---

frontend/src/App.tsx
frontend/src/components/auth/PrivateRoute.tsx
frontend/src/types/AuthTypes.ts

Closes #291 
* Add role checks for the different routes on FE
Looks at the routes at frontend\src\constants\Routes.ts
Sign in as volunteer.
1. check that you cannot access routes that start wth `/admin`
2. Check that you can access all other routes
Sign in as admin
1. Check that you cannot access routes that start with `/volunteer`
2. Check that you can access all other routes
* Checking to see if the routes behave as expected

Check Role in Private Route

---

frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
frontend/src/components/admin/posting/CreatePostingShifts.tsx
frontend/src/components/common/SideNavbarWithTitle.tsx
frontend/src/components/common/StickyBackNext.tsx
frontend/src/components/pages/admin/posting/CreatePostingBasicInfoPage.tsx
frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
frontend/src/components/pages/admin/posting/CreatePostingShiftsPage.tsx
frontend/src/theme/colors.ts

Closes #247 
* Implement sticky sidebar with proper background color with correct width/height
* Implement sticky back/next footer component
* Change the 3 posting pages to use new components
Changed pages:
1. go to route `/admin/posting/create/basic-info`
2. fill out form and submit, other wise visit other 2 pages manually: `/admin/posting/create/shifts` and `/admin/posting/create/review`
3. Throughout stages, sidebar is sticky, color is correct
4. Footer should be sticky and buttons work as intended
* Look and feel of changed pages
* Correctness/redundancy in code

Polish Admin Posting UI with sticky component

---

frontend/src/components/common/Loading.tsx
frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx

Closes #227 
* Implement loading component as per design
* Add usage to some existing queries + example usages specified in Figma
1. Go to any page that loads eg: `/admin/schedule/posting/1` or `volunteer/posting/1/availabilities`
2. Page should render partially with the loading component at the start
* Loading look and feel
* Implementation of loading comp + usage

Add Loading component + usages

---

frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
frontend/src/utils/DateTimeUtils.ts

* Fetch posting details from the api
1. Login as admin
2. Go to /admin/schedule/posting/1
3. Check that the posting title and branch name are accurate to the posting
4. Click review
5. check that the posting name is correct above the table
6. Repeat 2-5 for /admin/schedule/posting/2
* functionality :')

Fetch posting details in admin schedule page

---

frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx

1. Login as admin and go to /admin/posting/create/basic-info
2. Fill in everything except for skills
3. Ensure that you can't navigate to step 2
4. Fill in everything except for employees
5. Ensure that you can't navigate to the next step
* Functionality

Prevent next when no skills or employees

---

frontend/src/components/auth/Login.tsx

N/A
* Removes the sign up button from the login page
1. Click preview deploy link
2. Verify that login page no longer contains signup button
* N/A

Remove sign up button from login page

---

frontend/src/components/pages/Default.tsx

N/A
* Redirect to browse postings page from home page for volunteers
1. Click on preview deploy link
2. Login as a volunteer
3. Verify that you see the browse postings page after logging in
* N/A

Redirect to browse posting page from home page for volunteers

---

frontend/src/components/pages/Default.tsx
frontend/src/components/volunteer/PostingCard.tsx

Closes #335
1. Login as admin and go to `/`
2. Check that all postings are displayed
3. Click on `Edit Schedule` to go to a posting
* It works

create ui for admin schedule

---

frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx

Closes #327
* Add unique key to table row of update select availability table for volunteer flow
1. Issue described in ticket no longer reproducible

Fix bad key for table row - react not updating properly

---

frontend/src/index.tsx

Closes #328 
Currently, when you log in and don't log out, after a few hours you will be unable to properly load data in the application and you will be unable to logout. The issues is that calling FirebaseAdmin to refresh the token throws an `TOKEN_EXPIRED` [error code](https://firebase.google.com/docs/reference/rest/auth/#section-refresh-token). This means that the refresh token (stored in the cookies) is expired.
This solution will logout the user when we fail to refresh the token, because it assumes that the refresh token has expired. The only way to get a new one is to login again.
In the future, we would want the refresh token to not expire so frequently, but this requires more research. 
Test locally:
1. Go to `frontend/src/index.tsx` and replace the `if` condition on line 59 to be …

Logout user when token is expired

---

frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
frontend/src/components/volunteer/shifts/VolunteerShiftsTableRow.tsx

Closes #334 #333 
1. Go to `/volunteer/shifts` and click on Browse Volunteer Postings (this button appears when there are no shifts)
2. It should take you to Browse Postings
1. Go to `/volunteer/shifts`
2. Find a shift in the table (may need to click Requests Pending Confirmation)
3. Click `Go to Posting`
4. This should take you to the posting's details page

Fix My Shifts Table Links

---

frontend/src/components/pages/Default.tsx
frontend/src/components/pages/NewAccountPage.tsx

Closes #360 
* Added placeholder profile image
* Added two buttons ("Upload Photo" and "Remove Photo")
* Added State to the profile so it can update
1. Login to application
2. View the header of the main page
* Is the styling okay?
* Should I implement more functionality for buttons in this ticket?

Implement Account Creation Header

---

frontend/src/components/admin/DeleteModal.tsx

Closes #347 
* Created generic delete modal
1. Currently unable to test, interface that this is meant to be used on (deleting a posting as admin) is not yet made. However, this format follows other modals implemented.

Generic Delete Modal (#347)

---

frontend/src/App.tsx
frontend/src/components/pages/CreateAccountPage.tsx
frontend/src/constants/Routes.ts

Closes #340 
* Implemented frontend of create account landing page
1. Import component in App.tsx to /signup route
2. Go to localhost:3000/signup

Create Account Landing Page

---

frontend/src/App.tsx
frontend/src/constants/Routes.ts

Closes #351 
* added a new route in App.tsx for account creation (/new-account)
1. navigate to /new-account, verify it displays the following
* verify the above

Create new route for account creation

---

frontend/src/App.tsx
frontend/src/components/auth/PasswordResetSuccess.tsx
frontend/src/constants/Routes.ts

Closes #217 
* Created page, added necessary routing
1. go to http://localhost:3000/password-reset-success

Created password change successful page

---

frontend/src/components/auth/ResetPassword.tsx
frontend/src/components/pages/CreateAccountPage.tsx

Closes #216 
* Implemented page for resetting password (pg where you enter your email) 
1. go to localhost:3000/reset-password

Reset Password Page

---

frontend/src/components/auth/DoneResetPassword.tsx

Closes #218 
* Created the following static page
1. Navigate to http://localhost:3000/done-reset-password, verify the page displays the above ^ 
* the page created matches the design on Figma (shown below)

Create Email Sent Page

---

frontend/src/components/admin/AdminHomepageHeader.tsx
frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx

Closes #345 
* Created `AdminHomepageHeader.tsx` component under `frontend/component/admin/AdminHomepageHeader.tsx`
* Header takes in one boolean prop `isSuperAdmin`
1. Homepage currently does not exist, so component is mounted on `http://localhost:3000/admin/schedule/posting/1`
2. Check that the header for admin and super admin look good

Create admin homepage header component

---

backend/graphql/resolvers/authResolvers.ts
backend/graphql/types/authType.ts
backend/services/implementations/authService.ts
backend/services/implementations/userService.ts
backend/services/interfaces/authService.ts
backend/services/interfaces/userService.ts
backend/types.ts
frontend/package.json
frontend/src/APIClients/AuthAPIClient.ts
frontend/yarn.lock

Closes #289
* Removed google auth from frontend and backend (see ticket description for details)
1. Check that the google auth was successfully removed?

Remove google auth

---

frontend/src/App.tsx
frontend/src/components/pages/admin/AdminHomepage.tsx
frontend/src/constants/Routes.ts

Closes #355 
* Added route to `App.tsx` and `Routes.ts`
* Added empty component in `frontend\src\components\pages\admin` called `AdminHomepage.tsx`
1. http://localhost:3000/admin/ (empty page)

Add admin page and route

---

frontend/package.json
frontend/src/components/common/SignupNavbar.tsx
frontend/src/components/pages/NewAccountPage.tsx
frontend/src/components/user/AccountForm.tsx
frontend/src/components/user/ProfilePhotoForm.tsx
frontend/yarn.lock

Closes #352 
* Added an `AccountForm.tsx` component, which uses Formik to provide an account creation form.
* Refactored profile photo component into a new component `ProfilePhotoForm.tsx`.
* Implemented form functionality; form values are logged to console upon submission.
1. Navigate to `http://localhost:3000/new-account` and play with the form
2. Ensure that the expected form values are logged upon submission.
* Correct state management & use of Formik w/ Chakra UI.

Create account creation form component & page

---

frontend/src/components/auth/Login.tsx

Closes #214
* Styled the login page as per the Figma design using Chakra UI components
1. If logged into sistering, sign out
2. Visit the login page
* Verify that the UI looks like the Figma designs

creating login page ui

---

frontend/src/components/admin/AdminHomepageHeader.tsx
frontend/src/components/admin/BranchManagerModal.tsx
frontend/src/components/admin/BranchManagerTable.tsx
frontend/src/components/admin/DeleteModal.tsx
frontend/src/components/admin/EditModal.tsx
frontend/src/components/pages/admin/AdminHomepage.tsx
frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
frontend/src/constants/Tabs.ts
frontend/src/types/api/BranchTypes.ts

Closes #388 and #391
* Created `BranchManagerModal.tsx` in `frontend/components/admin/BranchManagerModal.tsx`
* Created `BranchManagerTable.tsx` used by `BranchManagerModal` in `frontend/components/admin/BranchManagerTable.tsx`
* `BranchManagerTable` component takes in a list of `BranchResponseDTO`
* Hooked up `BranchManagerModal` to call `branches` query and `createBranch` mutation
* Hooked up `BranchManagerTable` to call `updateBranch` and `deleteBranch` mutations
1. Go to `http://localhost:3000/admin/schedule/posting/1` where the admin homepage header is temporarily mounted
2. Click on the gear icon on the header
3. Check that the branch manager modal is shown
4. Test creating, updating, and deleting a branch

Create branch manager modal

---

backend/types.ts
frontend/src/components/pages/NewAccountPage.tsx
frontend/src/components/user/AccountForm.tsx
frontend/src/types/api/UserType.ts

Closes #354 
* Add queries to create employee and volunteer users (Rickson & Adriana)
* Added error handling and loading stuff (Rickson)
1. Go to Account Creation form and create a user

Create Employee/Volunteer User when "Create Account" is clicked (With GraphQL)

---

backend/prisma/migrations/20220628003855_user_invites_table/migration.sql
backend/prisma/schema.prisma

Closes #436 
* Added Prisma schema model
* Generated the migration file
1.  Migration didn't crash!
* Make sure this is not sus

Add User Invite Table

---

backend/graphql/types/userType.ts
backend/prisma/migrations/20220627232507_add_languages_to_user/migration.sql
backend/prisma/migrations/20220628224659_change_languages_param_to_array_of_language/migration.sql
backend/prisma/schema.prisma
backend/services/implementations/userService.ts
backend/types.ts
frontend/src/types/api/EmployeeTypes.ts
frontend/src/types/api/UserType.ts

Closes #425 
* Added to all relevant types in frontend and backend, added it to the 
1. Used graphql queries and migrations to test 
```
query AdminUserManagementPage_Users {
employeeUsers {
id
title
firstName
lastName
email
phoneNumber
branchId
languages
}
volunteerUsers {
id
firstName
lastName
email
phoneNumber
pronouns
languages
skills {
id
name
}
branches {
id
name
}
}
}
mutation CreateUser($employeeInfo: CreateEmployeeUserDTO!) {
createEmployeeUser(employeeUser: $employeeInfo) {
id
firstName
languages
}
}
mutation UpdateUsers(
$eid: ID!
$employeeInfo: UpdateEmployeeUserDTO!
$vid: ID!
$volunteerInfo: UpdateVolunteerUserDTO!
) {
updateEmployeeUserById(id: $eid, employeeUser: $employeeInfo) {
id
title
firstName
lastName
email
phoneNumber
branchId
languages
}
updateVolunteerUserById(id: …
```

Add language field to user

---

frontend/src/components/common/SignupNavbar.tsx
frontend/src/components/user/AccountForm.tsx

Closes #406
* Implemented cleanup comments from #381, account creation form
1. Go to /new-account and ensure that clicking "Back to Main" takes you to the sistering.org homepage
2. On the same page, ensure clicking "I have read ... terms and conditions" opens the terms and conditions in a new tab
* Whether or not opening the terms and conditions form in a new tab is appropriate (or instead, should we open it in the same tab?)

Cleanup comments/suggestions in #381

---

backend/prisma/migrations/20220705005839_remove_map_from_email_role_change_role_type_to_role/migration.sql
backend/prisma/schema.prisma

* Types in user invite were wrong, changed to proper typing, made migration.

Updated InviteUser Model

---

frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
frontend/src/components/pages/admin/user/MultiBranchSelector.tsx
frontend/src/components/pages/admin/user/MultiUserDrawer.tsx
frontend/src/components/pages/admin/user/ProfileDrawer.tsx

https://app.zenhub.com/workspaces/sistering-614f8dad6afeb8001d428787/issues/uwblueprint/sistering/402
Closes #402 
* Utilized the Chakra UI Drawer and Menu components and customized them as per the designs
1. Visit `http://localhost:3000/admin/users` and verify the UI looks like the designs on Figma
* Does the handling of selected branches seem appropriate?

Creating user management side panel + branch selection menu

---

backend/graphql/index.ts
backend/graphql/resolvers/userResolvers.ts
backend/graphql/types/userType.ts
backend/services/implementations/userService.ts
backend/services/interfaces/userService.ts
backend/types.ts

Closes #437 
* Created resolver that handles creation of userInvite row.
1. Go to graphql playground
2. Use this mutation:
```
mutation testCreateUserInvite($email: String!) {
createUserInvite(email: $email, role: VOLUNTEER) {
pid
email
role
}
}
```
It should respond with the newly created row.

437 create send user invite resolver

---

frontend/src/App.tsx
frontend/src/components/admin/AdminHomepageHeader.tsx
frontend/src/components/admin/BranchManagerModal.tsx
frontend/src/components/admin/BranchManagerTable.tsx
frontend/src/components/pages/admin/AdminHomepage.tsx

Closes #422, #426
* Added query data for posting cards in admin homepage
* Added query data for branches in admin homepage
* Postings should be sorted under each status tab (unscheduled, scheduled, past, draft)
1. Go to `http://localhost:3000/admin` and check that postings are properly shown under each tab
2. Check branches are shown in the branch dropdown

Integrate query data with admin homepage

---

backend/services/implementations/branchService.ts
frontend/src/components/admin/BranchManagerModal.tsx

Closes #447
* Added `sortBy` option in `prisma.branch.findMany` call to sort branches by id
1. Go to branch manager modal in `http://localhost:3000/admin` and try editing/deleting a branch
2. Branches should remain in the same order

Fix branches query to sort by id

---

frontend/package.json
frontend/src/components/admin/users/ProfileDrawer.tsx
frontend/src/components/admin/users/UserManagementTableRow.tsx
frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx

Closes #453
* Created a table row using Chakra's `<Tr>`
* Added a sample ProfileDrawer to verify the view details functionality
1. Login as admin and navigate to `/admin/users` and interact with the table, ensuring the row changes color when clicked
2. Click the three dots on the right and confirm the ProfileDrawer functionality
* In the code, please review how the `onCheck` functionality works with the table row, and the sample ProfileDrawer implementation.

Create users table row

---

backend/services/implementations/authService.ts

Hot fix for broken isAuth methods

deprecate is authorized email verify check

---

frontend/src/components/admin/AdminUserManagementPageHeader.tsx
frontend/src/components/pages/admin/AdminHomepage.tsx
frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx

Closes #471, #472
* Created `AdminUserManagementPageHeader.tsx` component in `frontend/src/components/admin` and mounted on `AdminUserManagementPage`
* Added `Navbar` to `AdminUserManagementPage` as well
* Hooked up `ProfileDrawer` component to "Edit Branch Access" button
* Hooked up branches query to branches dropdown
1. Go to `http://localhost:3000/admin/users` where the header is mounted
2. Check that the header looks good

Admin User Management Page Header

---

backend/prisma/seed.ts
backend/services/implementations/userService.ts
frontend/src/App.tsx
frontend/src/components/pages/EditAccountPage.tsx
frontend/src/components/pages/NewAccountPage.tsx
frontend/src/components/user/AccountForm.tsx
frontend/src/components/user/fields/SelectorField.tsx
frontend/src/components/user/fields/TextField.tsx
frontend/src/constants/Routes.ts
frontend/src/types/api/LanguageTypes.ts
frontend/src/types/api/UserType.ts

Closes #431 
Closes #498 
* Refactored `AccountForm` components into separate field components (`TextField` and `SelectorField`)
* Made `AccountForm` dynamic (i.e. components can pass in field data to pre-populate the form => this is used for editing)
* Reworked some of the AccountForm visuals & functions
* Fixed Volunteer/Employee User DTO types to match backend request model
* Created the EditAccountPage, which recycles the `AccountForm` component
* Updated seed data to include admin IDs in the employee table
* Reworked `updateEmployeeUserById()` in the backend to not assume user's role to be volunteer
* Protected `ADMIN_HOMEPAGE` to admin only
* (Sorry for the long change-list! A lot of these are bug fixes to existing code; the main focus of this ticket are in `AccountForm.tsx` and …

Admin/Volunteer edit account form + Update seed data

---

frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx

Closes #408 
* Added success toast to page component, toggled by the temporary button
1. Navigate to `http://localhost:3000/admin/users` and test the "Add Users to Branch" button
* Functionality

Add success toast for adding users to branches

---

frontend/src/components/admin/AdminUserManagementPageHeader.tsx
frontend/src/components/admin/UserInvitesModal.tsx
frontend/src/components/admin/UserInvitesTable.tsx
frontend/src/components/admin/schedule/AdminScheduleTableDate.tsx
frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
frontend/src/theme/index.ts
frontend/src/types/api/UserInviteTypes.ts
frontend/src/utils/DateTimeUtils.ts

Closes #479
* Created `UserInvitesModal.tsx` and `UserInvitesTable.tsx` in `frontend/src/components/admin`
* Hooked up modal to "Invitations" button in `AdminUserManagementPageHeader.tsx`
* Created `UserInviteTypes.ts` and added `UserInviteDTO`
* Made some changes to the Table brand theme
1. Go to `http://localhost:3000/admin/users`
2. Click on "Invitations" button to open the modal
3. Check modal looks good

Pending invitations modal

---

frontend/src/components/common/Navbar.tsx

hooked up edit profile page to navbar

edit profile page

---

frontend/src/components/common/Navbar.tsx

Closes #533 
* Added link to navbar UI
1. Login as admin and as volunteer and check if clicking on logo brings user to respective homepage

Link Sistering logo to user homepage :sparkles:

---

backend/graphql/index.ts
backend/graphql/resolvers/userResolvers.ts
backend/graphql/types/userType.ts
backend/services/implementations/userService.ts
backend/services/interfaces/userService.ts
backend/types.ts
frontend/src/components/admin/UserInvitesModal.tsx
frontend/src/components/admin/UserInvitesTable.tsx
frontend/src/types/api/UserInviteTypes.ts

Closes #516
* Created query resolver for all user invites
* Integrated user invites query and delete user mutation
1. Go to `http://localhost:3000/admin/users`
2. Open invitations modal
3. Create some sample invitations by clicking on "+" button 
4. Open the invitations modal
5. Check that the invitations just created are shown
6. Check that deleting an invitation works

Integrate User Invites Modal with Backend

---

backend/graphql/resolvers/authResolvers.ts
backend/graphql/resolvers/userResolvers.ts
backend/services/implementations/authService.ts
backend/services/interfaces/authService.ts

Closes #570 
* Remove all uses of the `sendEmailVerificationLink` method
1. Login as an admin and send a user invite (either volunteer or employee)
2. Use the user invite to create an account
3. Verify that a verification email is **not** sent after account creation
* Correctness

Remove all uses of sendEmailVerificationLink method

---

backend/services/implementations/skillService.ts
frontend/src/components/admin/AdminHomepageHeader.tsx
frontend/src/components/admin/BranchManagerModal.tsx
frontend/src/components/admin/BranchManagerTable.tsx
frontend/src/components/admin/SettingManagerModal.tsx
frontend/src/components/admin/SkillsManagerTable.tsx
frontend/src/components/user/AccountForm.tsx

Closes #536
* Created `SkillsManagerTable.tsx` in `frontend/components/admin` used in `BranchManagerModal`
* Skills manager essentially does the same thing as the branch manager but for skills
* Modified `BranchManagerModal` to now include `SkillsManagerTable`
1. Go to `http://localhost:3000/admin`
2. Click on the gear icon to open the manager
3. Click on the `Skills` tab for the skills manager
4. Test CRUD operations for skills

Skills Manager

---

frontend/src/components/user/AccountForm.tsx

…r and admin account forms
Closes #561 
1. Go to volunteer account, check edit account profile
2. Go to admin account , check edit account profile
3. Check admin and volunteer create account forms
Volunteer Account Form
Employee Account Form

Fixed non aligned tags in account forms

---

backend/graphql/index.ts
backend/graphql/resolvers/languageResolvers.ts
backend/graphql/types/languageType.ts
backend/graphql/types/userType.ts
backend/prisma/migrations/20220816000054_add_languages_table/migration.sql
backend/prisma/schema.prisma
backend/prisma/seed.ts
backend/services/implementations/branchService.ts
backend/services/implementations/languageService.ts
backend/services/implementations/skillService.ts
backend/services/implementations/userService.ts
backend/services/interfaces/languageService.ts
backend/types.ts
frontend/src/components/admin/LanguageManagerTable.tsx
frontend/src/components/admin/SettingManagerModal.tsx
frontend/src/components/admin/SkillsManagerTable.tsx
frontend/src/components/pages/EditAccountPage.tsx
frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
frontend/src/components/user/AccountForm.tsx
frontend/src/types/api/EmployeeTypes.ts
frontend/src/types/api/UserType.ts

Closes #501, #544 
* Created table, types, and resolvers for languages in backend
* Created language manager in frontend
1. Go to `http://localhost:3000/admin`
2. Click on gear icon
3. Click on languages tab
4. Test CRUD operations on languages

Make Languages Dynamic and Add Language Manager

---

frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx

Closes #617
* Removed minH on Box so background color now spans full height of box
1. Go to `http://localhost:3000/admin/schedule/posting/{id}`
2. Check no overflow anymore

Fix page overflow on Admin Schedule Review Page

---

frontend/src/components/admin/AddAdminModal.tsx
frontend/src/components/admin/AddVolunteerModal.tsx

Closes #630 
* Added a refetch query to admin invite mutation
1. Invite a super admin and check if invite can be viewed without having to refresh page
* Correctness

Add a refetch query to admin invite mutation :sparkles:

---

backend/graphql/resolvers/postingResolvers.ts
backend/graphql/types/postingType.ts
backend/services/implementations/postingService.ts
backend/services/interfaces/postingService.ts
frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx

Closes #612
* If volunteer is not in posting branch, then redirect to not found page
1. Log in as volunteer
2. Try to see posting details for branch current volunteer is not in
3. Check you are redirected to not found page

Only show volunteer posting details if user in branch

---

frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx

revert https://github.com/uwblueprint/sistering/commit/56f1b2986c4131594c755fe1a776ffec08ae452e

Fix publish guard bug
